const test = require("node:test");
const assert = require("node:assert/strict");
const { DEFAULT_THEME } = require("../schema/theme-schema");
const { getRegistry } = require("../registry/options");
const { resolveDesign, resolveDesignBundle } = require("../design/resolve-design");
const { assertRegistryContract } = require("../design/registry-contract");
const duck = require("../elements/decorations/logos/duck-vector");
const { createStressFixtures } = require("../workbench/parity-check");
const {
  generateFiles,
  generateResolvedFiles,
  escapeLatex,
  aspectRatioOption
} = require("../generators/latex");

test("escapes LaTeX-sensitive user text", () => {
  assert.equal(escapeLatex("A&B_50%"), "A\\&B\\_50\\%");
});

test("maps aspect ratios to Beamer class options", () => {
  assert.equal(aspectRatioOption("16:9"), "aspectratio=169");
  assert.equal(aspectRatioOption("4:3"), "aspectratio=43");
});

test("generates a complete Beamer file set", () => {
  const files = generateFiles(DEFAULT_THEME, getRegistry());
  assert.deepEqual(Object.keys(files).sort(), [
    "README.md",
    "content/figures.tex",
    "content/overview.tex",
    "content/tables.tex",
    "main.tex",
    "theme.cls",
    "theme.json"
  ]);
  assert.match(files["main.tex"], /\\documentclass\[10pt\]\{theme\}/);
  assert.match(files["theme.cls"], /\\definecolor\{bfPrimary\}\{HTML\}\{456990\}/);
  assert.match(files["theme.cls"], /\\setbeamertemplate\{itemize item\}\{\\ding\{109\}\}/);
  assert.match(files["README.md"], /Generated by BeamerForge/);
});

test("all renderer parity stress fixtures resolve and generate stable overview landmarks", () => {
  for (const fixture of createStressFixtures()) {
    const bundle = resolveDesignBundle(fixture.theme, getRegistry());
    const files = generateResolvedFiles(bundle.design);

    assert.equal(bundle.design.capabilities.html, true, fixture.id);
    assert.equal(bundle.design.capabilities.latex, true, fixture.id);
    assert.match(files["theme.cls"], bundle.design.canvas.aspectRatio === "4:3" ? /aspectratio=43/ : /aspectratio=169/);
    assert.ok(files["content/overview.tex"].includes(bundle.design.content.sampleTitle), fixture.id);
    assert.equal(files["theme.cls"].includes("tikzpicture"), fixture.id === "duck", fixture.id);
  }
});

test("generates render files directly from one resolved design", () => {
  const files = generateResolvedFiles(resolveDesign(DEFAULT_THEME, getRegistry()));

  assert.deepEqual(Object.keys(files).sort(), [
    "README.md",
    "content/figures.tex",
    "content/overview.tex",
    "content/tables.tex",
    "main.tex",
    "theme.cls"
  ]);
  assert.match(files["theme.cls"], /\\definecolor\{bfPrimary\}\{HTML\}\{456990\}/);
  assert.match(
    files["content/overview.tex"],
    /The instant HTML preview and authoritative PDF use the same resolved design\./
  );
  assert.equal(Object.hasOwn(files, "theme.json"), false);
});

test("renders exact 4:3 dark colors from a resolved design", () => {
  const theme = structuredClone(DEFAULT_THEME);
  theme.foundation.aspectRatio = "4:3";
  theme.colors.paletteId = "midnight-blue";
  theme.colors.background = "#0D1B2A";
  theme.colors.primary = "#4A90D9";
  theme.colors.accent = "#D4A843";
  theme.colors.text = "#F7FBFF";
  theme.colors.blockBody = "#1B2A4A";
  theme.colors.alert = "#D4A843";

  const files = generateResolvedFiles(resolveDesign(theme, getRegistry()));

  assert.match(files["theme.cls"], /\\LoadClass\[10pt,aspectratio=43\]\{beamer\}/);
  assert.match(files["theme.cls"], /\\definecolor\{bfBackground\}\{HTML\}\{0D1B2A\}/);
  assert.match(files["theme.cls"], /\\definecolor\{bfPrimary\}\{HTML\}\{4A90D9\}/);
});

test("resolved-file generation never accepts or looks up a registry", () => {
  const design = resolveDesign(DEFAULT_THEME, getRegistry());
  const explosiveRegistry = new Proxy({}, {
    get() {
      throw new Error("registry lookup during rendering");
    }
  });

  assert.equal(generateResolvedFiles.length, 1);
  assert.doesNotThrow(() => generateResolvedFiles(design, explosiveRegistry));
});

test("generates Neuton fontspec and soft miniframes variants", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "neuton";
  theme.fonts.title = "neuton";
  theme.navigation.style = "soft-miniframes";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\usepackage\{fontspec\}/);
  assert.match(
    files["theme.cls"],
    /\\setmainfont\[Path=font\/,BoldFont=Neuton-Bold\.ttf,ItalicFont=Neuton-Italic\.ttf\]\{Neuton-Regular\.ttf\}/
  );
  assert.match(files["theme.cls"], /\\useoutertheme\[subsection=false\]\{miniframes\}/);
});

test("sets Beamer sans family for bundled local fonts", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "orbitron";
  theme.fonts.title = "orbitron";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\setmainfont\[Path=font\/\]\{Orbitron\.ttf\}/);
  assert.match(files["theme.cls"], /\\setsansfont\[Path=font\/\]\{Orbitron\.ttf\}/);
});

test("uses a distinct title font in generated Beamer font settings", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "lato";
  theme.fonts.title = "orbitron";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\setmainfont\[Path=font\/\]\{Lato\.ttf\}/);
  assert.match(files["theme.cls"], /\\newfontfamily\\bfTitleFont\[Path=font\/\]\{Orbitron\.ttf\}/);
  assert.match(
    files["theme.cls"],
    /\\setbeamerfont\{title\}\{family=\\bfTitleFont,series=\\bfseries,size=\\huge\}/
  );
  assert.match(
    files["theme.cls"],
    /\\setbeamerfont\{frametitle\}\{family=\\bfTitleFont,series=\\bfseries,size=\\Large\}/
  );
});

test("generates navigation footlines from registry metadata", () => {
  const registry = getRegistry();
  const noneTheme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  noneTheme.navigation.style = "none";
  const footerTheme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  footerTheme.navigation.style = "soft-miniframes";

  const noneFiles = generateFiles(noneTheme, registry);
  const footerFiles = generateFiles(footerTheme, registry);

  assert.doesNotMatch(noneFiles["theme.cls"], /\\inserttotalframenumber/);
  assert.match(footerFiles["theme.cls"], /\\useoutertheme\[subsection=false\]\{miniframes\}/);
  assert.match(footerFiles["theme.cls"], /\\inserttotalframenumber/);
});

test("generates required packages for expanded bullet styles", () => {
  const registry = getRegistry();
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.bullets.style = "tikz-octagon";

  const files = generateFiles(theme, registry);

  assert.match(files["theme.cls"], /\\RequirePackage\{tikz\}/);
  assert.match(files["theme.cls"], /regular polygon sides=8/);
});

test("overview content includes a block so block styles are visible", () => {
  const files = generateFiles(DEFAULT_THEME, getRegistry());

  assert.match(files["content/overview.tex"], /\\begin\{block\}\{Design note\}/);
  assert.match(files["content/overview.tex"], /same resolved design/);
});

test("uses resolved package title semantics for an aliased font key", () => {
  const registry = getRegistry();
  registry.fonts["custom-package-title"] = {
    ...registry.fonts.times,
    id: "not-a-known-catalog-id",
    label: "Custom Package Title",
    latexTitlePackage: "\\usepackage{mathptmx}",
    latexTitleFamily: "ptm"
  };
  const theme = structuredClone(DEFAULT_THEME);
  theme.fonts.title = "custom-package-title";

  const files = generateFiles(theme, registry);

  assert.match(files["theme.cls"], /\\usepackage\{mathptmx\}/);
  assert.match(files["theme.cls"], /\\newcommand\{\\bfTitleFont\}\{\\fontfamily\{ptm\}\\selectfont\}/);
});

test("renders title pages by resolved layout when the catalog ID is aliased", () => {
  const registry = getRegistry();
  registry.titlePages.alias = {
    ...registry.titlePages["left-curtain"],
    id: "centered",
    layout: "left-curtain"
  };
  const theme = structuredClone(DEFAULT_THEME);
  theme.titlePage.layout = "alias";

  const files = generateFiles(theme, registry);

  assert.match(files["theme.cls"], /leftskip=1\.2cm,rightskip=1\.2cm/);
});

test("dispatches trusted logo rendering by resolved vector semantics", () => {
  const registry = getRegistry();
  registry.logos["duck-alias"] = {
    ...registry.logos.duck,
    id: "different-duck-catalog-id"
  };
  registry.logos["null-vector-alias"] = {
    ...registry.logos.none,
    id: "non-none-catalog-id",
    label: "No Vector Alias"
  };

  const duckTheme = structuredClone(DEFAULT_THEME);
  duckTheme.decorations.cornerLogo.id = "duck-alias";
  const nullTheme = structuredClone(DEFAULT_THEME);
  nullTheme.decorations.cornerLogo.id = "null-vector-alias";

  assert.match(generateFiles(duckTheme, registry)["theme.cls"], /\\begin\{tikzpicture\}/);
  assert.doesNotMatch(generateFiles(nullTheme, registry)["theme.cls"], /\\begin\{tikzpicture\}/);
});

test("renders a new trusted vector from its actual art without vector ID dispatch", () => {
  const registry = getRegistry();
  const futureVector = structuredClone(duck);
  futureVector.id = "future-vector";
  futureVector.primitives[3].cx = 4.2;
  registry.logos.future = {
    ...registry.logos.duck,
    id: "future",
    label: "Future Vector",
    vector: futureVector,
    vectorId: "future-vector",
    previewUrl: "/assets/generated/logos/future-vector.svg"
  };
  const theme = structuredClone(DEFAULT_THEME);
  theme.decorations.cornerLogo.id = "future";

  const classFile = generateFiles(theme, registry)["theme.cls"];
  assert.match(classFile, /\\definecolor\{bfvI[0-9a-f]+K626c61636b\}/);
  assert.match(classFile, /\(4\.2,1\.2\) circle/);
});

test("raw wrapper serializes a normalized complete legacy theme", () => {
  const theme = structuredClone(DEFAULT_THEME);
  delete theme.identity.title;
  delete theme.colors.blockBody;
  delete theme.colors.alert;
  delete theme.contentDefaults.sampleBullets;

  const serialized = JSON.parse(generateFiles(theme, getRegistry())["theme.json"]);

  assert.equal(serialized.identity.title, "");
  assert.equal(serialized.colors.blockBody, theme.colors.background);
  assert.equal(serialized.colors.alert, theme.colors.accent);
  assert.deepEqual(serialized.contentDefaults.sampleBullets, DEFAULT_THEME.contentDefaults.sampleBullets);
});

test("raw wrapper invokes one resolved bundle pipeline", () => {
  let calls = 0;
  const files = generateFiles(DEFAULT_THEME, getRegistry(), {
    resolveDesignBundle(theme, registry) {
      calls += 1;
      return resolveDesignBundle(theme, registry);
    }
  });

  assert.equal(calls, 1);
  assert.equal(JSON.parse(files["theme.json"]).identity.title, DEFAULT_THEME.identity.title);
});

test("throws a useful error for invalid theme IDs", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.navigation.style = "missing-nav";

  assert.throws(
    () => generateFiles(theme, getRegistry()),
    /Invalid theme: .*navigation\.style/
  );
});

test("generates a trusted top-right duck logo overlay", () => {
  const theme = structuredClone(DEFAULT_THEME);
  theme.decorations.cornerLogo = { id: "duck", position: "top-right", size: "small", scope: "content-frames" };
  const files = generateFiles(theme, getRegistry());
  assert.match(files["theme.cls"], /\\begin\{tikzpicture\}/);
  assert.doesNotMatch(files["theme.cls"], /\\includegraphics.*corner-logo\.svg/);
  assert.match(files["theme.cls"], /background canvas/);
  assert.match(files["theme.cls"], /0\.8cm/);
  assert.match(files["theme.cls"], /\\begin\{tikzpicture\}\[scale=0\.133333\]/);
  assert.equal((files["theme.cls"].match(/^\s*\\(?:fill|draw)\b/gm) || []).length, 5);
});

test("medium duck logo scale is derived from vector viewBox width", () => {
  const theme = structuredClone(DEFAULT_THEME);
  theme.decorations.cornerLogo = { id: "duck", position: "top-left", size: "medium", scope: "all-frames" };
  const classFile = generateFiles(theme, getRegistry())["theme.cls"];

  assert.match(classFile, /\{1\.2cm\}/);
  assert.match(classFile, /\\begin\{tikzpicture\}\[scale=0\.2\]/);
});

test("logo scale uses shared bounded decimal formatting", () => {
  const design = structuredClone(resolveDesign(DEFAULT_THEME, getRegistry()));
  design.components.cornerLogo = {
    ...design.components.cornerLogo,
    id: "duck",
    vectorId: "duck",
    vector: duck,
    sizeUnits: 0.1 + 0.2
  };

  const classFile = generateResolvedFiles(design)["theme.cls"];
  assert.match(classFile, /\\begin\{tikzpicture\}\[scale=0\.05\]/);
  assert.doesNotMatch(classFile, /0\.05000000000000001/);
});

test("logo scale applies equally to TikZ line coordinates and stroke width", () => {
  const registry = getRegistry();
  const lineVector = {
    id: "line-logo",
    viewBox: [0, 0, 6, 4],
    colors: { ink: "#17202A" },
    primitives: [{
      type: "line",
      x1: 0.1,
      y1: 0.1,
      x2: 5.9,
      y2: 3.9,
      stroke: "ink",
      strokeWidth: 0.2
    }]
  };
  registry.logos["line-logo"] = {
    ...registry.logos.duck,
    id: "line-logo",
    label: "Line Logo",
    vector: lineVector,
    vectorId: "line-logo",
    previewUrl: "/assets/generated/logos/line-logo.svg"
  };
  const theme = structuredClone(DEFAULT_THEME);
  theme.decorations.cornerLogo = {
    id: "line-logo",
    position: "top-right",
    size: "small",
    scope: "content-frames"
  };

  const classFile = generateFiles(theme, registry)["theme.cls"];
  assert.match(classFile, /\\begin\{tikzpicture\}\[scale=0\.133333\]/);
  assert.match(classFile, /line width=0\.026667cm/);
  assert.doesNotMatch(classFile, /line width=0\.2cm/);
});

test("every registry-accepted boundary vector generates at both supported logo sizes", () => {
  const registry = getRegistry();
  const boundaryVector = {
    id: "boundary-polygon-logo",
    viewBox: [0, 0, 0.00012, 0.00012],
    colors: { ink: "#17202A" },
    primitives: [{
      type: "polygon",
      points: [[0, 0], [0.00012, 0], [0, 0.00012]],
      fill: "ink"
    }]
  };
  registry.logos["boundary-polygon-logo"] = {
    ...registry.logos.duck,
    id: "boundary-polygon-logo",
    label: "Boundary Polygon Logo",
    vector: boundaryVector,
    vectorId: "boundary-polygon-logo",
    previewUrl: "/assets/generated/logos/boundary-polygon-logo.svg"
  };
  assert.doesNotThrow(() => assertRegistryContract(registry));

  for (const [size, scale] of [["small", "6666.666667"], ["medium", "10000"]]) {
    const theme = structuredClone(DEFAULT_THEME);
    theme.decorations.cornerLogo = {
      id: "boundary-polygon-logo",
      position: "top-right",
      size,
      scope: "content-frames"
    };
    assert.match(
      generateFiles(theme, registry)["theme.cls"],
      new RegExp(`\\\\begin\\{tikzpicture\\}\\[scale=${scale.replace(".", "\\.")}\\]`)
    );
  }
});
