const test = require("node:test");
const assert = require("node:assert/strict");
const { DEFAULT_THEME } = require("../schema/theme-schema");
const { getRegistry } = require("../registry/options");
const { generateFiles, escapeLatex, aspectRatioOption } = require("../generators/latex");

test("escapes LaTeX-sensitive user text", () => {
  assert.equal(escapeLatex("A&B_50%"), "A\\&B\\_50\\%");
});

test("maps aspect ratios to Beamer class options", () => {
  assert.equal(aspectRatioOption("16:9"), "aspectratio=169");
  assert.equal(aspectRatioOption("4:3"), "aspectratio=43");
});

test("generates a complete Beamer file set", () => {
  const files = generateFiles(DEFAULT_THEME, getRegistry());
  assert.deepEqual(Object.keys(files).sort(), [
    "README.md",
    "content/figures.tex",
    "content/overview.tex",
    "content/tables.tex",
    "main.tex",
    "theme.cls",
    "theme.json"
  ]);
  assert.match(files["main.tex"], /\\documentclass\[10pt\]\{theme\}/);
  assert.match(files["theme.cls"], /\\definecolor\{bfPrimary\}\{HTML\}\{456990\}/);
  assert.match(files["theme.cls"], /\\setbeamertemplate\{itemize item\}\{\\ding\{109\}\}/);
  assert.match(files["README.md"], /Generated by BeamerForge/);
});

test("generates Neuton fontspec and soft miniframes variants", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "neuton";
  theme.fonts.title = "neuton";
  theme.navigation.style = "soft-miniframes";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\usepackage\{fontspec\}/);
  assert.match(
    files["theme.cls"],
    /\\setmainfont\[Path=font\/,BoldFont=Neuton-Bold\.ttf,ItalicFont=Neuton-Italic\.ttf\]\{Neuton-Regular\.ttf\}/
  );
  assert.match(files["theme.cls"], /\\useoutertheme\[subsection=false\]\{miniframes\}/);
});

test("sets Beamer sans family for bundled local fonts", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "orbitron";
  theme.fonts.title = "orbitron";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\setmainfont\[Path=font\/\]\{Orbitron\.ttf\}/);
  assert.match(files["theme.cls"], /\\setsansfont\[Path=font\/\]\{Orbitron\.ttf\}/);
});

test("uses a distinct title font in generated Beamer font settings", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "lato";
  theme.fonts.title = "orbitron";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\setmainfont\[Path=font\/\]\{Lato\.ttf\}/);
  assert.match(files["theme.cls"], /\\newfontfamily\\bfTitleFont\[Path=font\/\]\{Orbitron\.ttf\}/);
  assert.match(
    files["theme.cls"],
    /\\setbeamerfont\{title\}\{family=\\bfTitleFont,series=\\bfseries,size=\\huge\}/
  );
  assert.match(
    files["theme.cls"],
    /\\setbeamerfont\{frametitle\}\{family=\\bfTitleFont,series=\\bfseries,size=\\Large\}/
  );
});

test("generates navigation footlines from registry metadata", () => {
  const registry = getRegistry();
  const noneTheme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  noneTheme.navigation.style = "none";
  const footerTheme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  footerTheme.navigation.style = "soft-miniframes";

  const noneFiles = generateFiles(noneTheme, registry);
  const footerFiles = generateFiles(footerTheme, registry);

  assert.doesNotMatch(noneFiles["theme.cls"], /\\inserttotalframenumber/);
  assert.match(footerFiles["theme.cls"], /\\useoutertheme\[subsection=false\]\{miniframes\}/);
  assert.match(footerFiles["theme.cls"], /\\inserttotalframenumber/);
});

test("generates required packages for expanded bullet styles", () => {
  const registry = getRegistry();
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.bullets.style = "tikz-octagon";

  const files = generateFiles(theme, registry);

  assert.match(files["theme.cls"], /\\RequirePackage\{tikz\}/);
  assert.match(files["theme.cls"], /regular polygon sides=8/);
});

test("overview content includes a block so block styles are visible", () => {
  const files = generateFiles(DEFAULT_THEME, getRegistry());

  assert.match(files["content/overview.tex"], /\\begin\{block\}\{Design note\}/);
  assert.match(files["content/overview.tex"], /same theme tokens/);
});

test("throws a useful error for invalid theme IDs", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.navigation.style = "missing-nav";

  assert.throws(
    () => generateFiles(theme, getRegistry()),
    /Invalid theme: .*navigation\.style/
  );
});
