const test = require("node:test");
const assert = require("node:assert/strict");
const { DEFAULT_THEME } = require("../schema/theme-schema");
const { getRegistry } = require("../registry/options");
const { resolveDesign } = require("../design/resolve-design");
const {
  generateFiles,
  generateResolvedFiles,
  escapeLatex,
  aspectRatioOption
} = require("../generators/latex");

test("escapes LaTeX-sensitive user text", () => {
  assert.equal(escapeLatex("A&B_50%"), "A\\&B\\_50\\%");
});

test("maps aspect ratios to Beamer class options", () => {
  assert.equal(aspectRatioOption("16:9"), "aspectratio=169");
  assert.equal(aspectRatioOption("4:3"), "aspectratio=43");
});

test("generates a complete Beamer file set", () => {
  const files = generateFiles(DEFAULT_THEME, getRegistry());
  assert.deepEqual(Object.keys(files).sort(), [
    "README.md",
    "content/figures.tex",
    "content/overview.tex",
    "content/tables.tex",
    "main.tex",
    "theme.cls",
    "theme.json"
  ]);
  assert.match(files["main.tex"], /\\documentclass\[10pt\]\{theme\}/);
  assert.match(files["theme.cls"], /\\definecolor\{bfPrimary\}\{HTML\}\{456990\}/);
  assert.match(files["theme.cls"], /\\setbeamertemplate\{itemize item\}\{\\ding\{109\}\}/);
  assert.match(files["README.md"], /Generated by BeamerForge/);
});

test("generates render files directly from one resolved design", () => {
  const files = generateResolvedFiles(resolveDesign(DEFAULT_THEME, getRegistry()));

  assert.deepEqual(Object.keys(files).sort(), [
    "README.md",
    "content/figures.tex",
    "content/overview.tex",
    "content/tables.tex",
    "main.tex",
    "theme.cls"
  ]);
  assert.match(files["theme.cls"], /\\definecolor\{bfPrimary\}\{HTML\}\{456990\}/);
  assert.match(
    files["content/overview.tex"],
    /The instant HTML preview and authoritative PDF use the same resolved design\./
  );
  assert.equal(Object.hasOwn(files, "theme.json"), false);
});

test("renders exact 4:3 dark colors from a resolved design", () => {
  const theme = structuredClone(DEFAULT_THEME);
  theme.foundation.aspectRatio = "4:3";
  theme.colors.paletteId = "midnight-blue";
  theme.colors.background = "#0D1B2A";
  theme.colors.primary = "#4A90D9";
  theme.colors.accent = "#D4A843";
  theme.colors.text = "#F7FBFF";
  theme.colors.blockBody = "#1B2A4A";
  theme.colors.alert = "#D4A843";

  const files = generateResolvedFiles(resolveDesign(theme, getRegistry()));

  assert.match(files["theme.cls"], /\\LoadClass\[10pt,aspectratio=43\]\{beamer\}/);
  assert.match(files["theme.cls"], /\\definecolor\{bfBackground\}\{HTML\}\{0D1B2A\}/);
  assert.match(files["theme.cls"], /\\definecolor\{bfPrimary\}\{HTML\}\{4A90D9\}/);
});

test("resolved-file generation never accepts or looks up a registry", () => {
  const design = resolveDesign(DEFAULT_THEME, getRegistry());
  const explosiveRegistry = new Proxy({}, {
    get() {
      throw new Error("registry lookup during rendering");
    }
  });

  assert.equal(generateResolvedFiles.length, 1);
  assert.doesNotThrow(() => generateResolvedFiles(design, explosiveRegistry));
});

test("generates Neuton fontspec and soft miniframes variants", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "neuton";
  theme.fonts.title = "neuton";
  theme.navigation.style = "soft-miniframes";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\usepackage\{fontspec\}/);
  assert.match(
    files["theme.cls"],
    /\\setmainfont\[Path=font\/,BoldFont=Neuton-Bold\.ttf,ItalicFont=Neuton-Italic\.ttf\]\{Neuton-Regular\.ttf\}/
  );
  assert.match(files["theme.cls"], /\\useoutertheme\[subsection=false\]\{miniframes\}/);
});

test("sets Beamer sans family for bundled local fonts", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "orbitron";
  theme.fonts.title = "orbitron";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\setmainfont\[Path=font\/\]\{Orbitron\.ttf\}/);
  assert.match(files["theme.cls"], /\\setsansfont\[Path=font\/\]\{Orbitron\.ttf\}/);
});

test("uses a distinct title font in generated Beamer font settings", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.fonts.body = "lato";
  theme.fonts.title = "orbitron";

  const files = generateFiles(theme, getRegistry());

  assert.match(files["theme.cls"], /\\setmainfont\[Path=font\/\]\{Lato\.ttf\}/);
  assert.match(files["theme.cls"], /\\newfontfamily\\bfTitleFont\[Path=font\/\]\{Orbitron\.ttf\}/);
  assert.match(
    files["theme.cls"],
    /\\setbeamerfont\{title\}\{family=\\bfTitleFont,series=\\bfseries,size=\\huge\}/
  );
  assert.match(
    files["theme.cls"],
    /\\setbeamerfont\{frametitle\}\{family=\\bfTitleFont,series=\\bfseries,size=\\Large\}/
  );
});

test("generates navigation footlines from registry metadata", () => {
  const registry = getRegistry();
  const noneTheme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  noneTheme.navigation.style = "none";
  const footerTheme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  footerTheme.navigation.style = "soft-miniframes";

  const noneFiles = generateFiles(noneTheme, registry);
  const footerFiles = generateFiles(footerTheme, registry);

  assert.doesNotMatch(noneFiles["theme.cls"], /\\inserttotalframenumber/);
  assert.match(footerFiles["theme.cls"], /\\useoutertheme\[subsection=false\]\{miniframes\}/);
  assert.match(footerFiles["theme.cls"], /\\inserttotalframenumber/);
});

test("generates required packages for expanded bullet styles", () => {
  const registry = getRegistry();
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.bullets.style = "tikz-octagon";

  const files = generateFiles(theme, registry);

  assert.match(files["theme.cls"], /\\RequirePackage\{tikz\}/);
  assert.match(files["theme.cls"], /regular polygon sides=8/);
});

test("overview content includes a block so block styles are visible", () => {
  const files = generateFiles(DEFAULT_THEME, getRegistry());

  assert.match(files["content/overview.tex"], /\\begin\{block\}\{Design note\}/);
  assert.match(files["content/overview.tex"], /same resolved design/);
});

test("raw wrapper serializes a normalized complete legacy theme", () => {
  const theme = structuredClone(DEFAULT_THEME);
  delete theme.identity.title;
  delete theme.colors.blockBody;
  delete theme.colors.alert;
  delete theme.contentDefaults.sampleBullets;

  const serialized = JSON.parse(generateFiles(theme, getRegistry())["theme.json"]);

  assert.equal(serialized.identity.title, "");
  assert.equal(serialized.colors.blockBody, theme.colors.background);
  assert.equal(serialized.colors.alert, theme.colors.accent);
  assert.deepEqual(serialized.contentDefaults.sampleBullets, DEFAULT_THEME.contentDefaults.sampleBullets);
});

test("throws a useful error for invalid theme IDs", () => {
  const theme = JSON.parse(JSON.stringify(DEFAULT_THEME));
  theme.navigation.style = "missing-nav";

  assert.throws(
    () => generateFiles(theme, getRegistry()),
    /Invalid theme: .*navigation\.style/
  );
});

test("generates a trusted top-right duck logo overlay", () => {
  const theme = structuredClone(DEFAULT_THEME);
  theme.decorations.cornerLogo = { id: "duck", position: "top-right", size: "small", scope: "content-frames" };
  const files = generateFiles(theme, getRegistry());
  assert.match(files["theme.cls"], /\\begin\{tikzpicture\}/);
  assert.doesNotMatch(files["theme.cls"], /\\includegraphics.*corner-logo\.svg/);
  assert.match(files["theme.cls"], /background canvas/);
  assert.match(files["theme.cls"], /0\.8cm/);
});
